examples:
- 'examples/**/*'

dependecies:
- 'package.json'
- 'package-lock.json'

managers:
- 'src/managers/**/*'

structures:
- 'src/structures/**/*'

permissions:
- 'src/utils/Permission.ts'
- 'src/constants/permissions.ts'

intents:
- 'src/utils/Intents.ts'
- 'src/constants/intents.ts'

actions:
- 'src/actions/**/*'

client:
- 'src/client/Client.ts'

websocket:
- 'src/client/websocket/**/*'

utility:
- 'src/utils/**/*'

channels:
- '**/?(*Channel*).js'

roles:
- '**/?(*Role*).js'

exports:
- 'src/index.ts'
