actions:
  - src/actions/**/*
bitfields:
  - src/utils/bitfield/**/*
builders:
  - src/builders/**/*
channels:
  - '**/?(*Channel*).ts'
client:
  - src/client/Client.ts
dependecies:
  - package.json
  - package-lock.json
examples:
  - examples/**/*
exports:
  - src/index.ts
github:
  - .github/**/*
intents:
  - src/utils/bitfields/IntentsBitField.ts
transformers:
  - src/utils/managers/**/*
rest:
  - src/utils/rest/**/*
permissions:
  - src/utils/bitfields/PermissionsBitField.ts
roles:
  - '**/?(*Role*).ts'
structures:
  - src/structures/**/*
utility:
  - src/utils/**/*
websocket:
  - src/client/websocket/**/*
