on:
  push:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: yarn install
      run: yarn install
    - name: eslint
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: src
