on: [push, pull_request]

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: yarn install
      run: yarn install
    - name: tsc
      uses: icrawl/action-tsc@v1
